const VOKABELN = {
  begruessung: { name: "Begrüßung & Höflichkeit", icon: "👋", level: "A1", words: [
    { id: "b01", fr: "bonjour", de: "guten Tag" },
    { id: "b02", fr: "bonsoir", de: "guten Abend" },
    { id: "b03", fr: "bonne nuit", de: "gute Nacht" },
    { id: "b04", fr: "au revoir", de: "auf Wiedersehen" },
    { id: "b05", fr: "salut", de: "hallo / tschüss" },
    { id: "b06", fr: "merci", de: "danke" },
    { id: "b07", fr: "merci beaucoup", de: "vielen Dank" },
    { id: "b08", fr: "s'il vous plaît", de: "bitte (höflich)" },
    { id: "b09", fr: "s'il te plaît", de: "bitte (vertraut)" },
    { id: "b10", fr: "de rien", de: "gern geschehen" },
    { id: "b11", fr: "excusez-moi", de: "entschuldigen Sie" },
    { id: "b12", fr: "pardon", de: "Verzeihung" },
    { id: "b13", fr: "oui", de: "ja" },
    { id: "b14", fr: "non", de: "nein" },
    { id: "b15", fr: "comment allez-vous ?", de: "wie geht es Ihnen?" },
    { id: "b16", fr: "ça va ?", de: "wie geht's?" },
    { id: "b17", fr: "ça va bien", de: "mir geht es gut" },
    { id: "b18", fr: "je m'appelle...", de: "ich heiße..." },
    { id: "b19", fr: "enchanté(e)", de: "freut mich" },
    { id: "b20", fr: "à bientôt", de: "bis bald" },
    { id: "b21", fr: "à demain", de: "bis morgen" },
    { id: "b22", fr: "bienvenue", de: "willkommen" },
    { id: "b23", fr: "madame", de: "Frau" },
    { id: "b24", fr: "monsieur", de: "Herr" },
    { id: "b25", fr: "je suis désolé(e)", de: "es tut mir leid" },
    { id: "b26", fr: "bonne journée", de: "schönen Tag" },
    { id: "b27", fr: "avec plaisir", de: "mit Vergnügen" },
    { id: "b28", fr: "d'accord", de: "einverstanden" },
    { id: "b29", fr: "bien sûr", de: "natürlich" },
    { id: "b30", fr: "je ne comprends pas", de: "ich verstehe nicht" },
  ]},
  restaurant: { name: "Im Restaurant", icon: "🍽️", level: "A1", words: [
    { id: "r01", fr: "le restaurant", de: "das Restaurant" },
    { id: "r02", fr: "la carte", de: "die Speisekarte" },
    { id: "r03", fr: "le menu", de: "das Menü" },
    { id: "r04", fr: "l'entrée", de: "die Vorspeise" },
    { id: "r05", fr: "le plat principal", de: "das Hauptgericht" },
    { id: "r06", fr: "le dessert", de: "der Nachtisch" },
    { id: "r07", fr: "la boisson", de: "das Getränk" },
    { id: "r08", fr: "l'eau", de: "das Wasser" },
    { id: "r09", fr: "le vin", de: "der Wein" },
    { id: "r10", fr: "la bière", de: "das Bier" },
    { id: "r11", fr: "le café", de: "der Kaffee" },
    { id: "r12", fr: "le thé", de: "der Tee" },
    { id: "r13", fr: "le pain", de: "das Brot" },
    { id: "r14", fr: "le fromage", de: "der Käse" },
    { id: "r15", fr: "la viande", de: "das Fleisch" },
    { id: "r16", fr: "le poisson", de: "der Fisch" },
    { id: "r17", fr: "la salade", de: "der Salat" },
    { id: "r18", fr: "la soupe", de: "die Suppe" },
    { id: "r19", fr: "l'addition", de: "die Rechnung" },
    { id: "r20", fr: "le pourboire", de: "das Trinkgeld" },
    { id: "r21", fr: "une table pour deux", de: "ein Tisch für zwei" },
    { id: "r22", fr: "je voudrais...", de: "ich hätte gern..." },
    { id: "r23", fr: "l'addition, s'il vous plaît", de: "die Rechnung, bitte" },
    { id: "r24", fr: "c'est délicieux", de: "das ist köstlich" },
    { id: "r25", fr: "le serveur", de: "der Kellner" },
    { id: "r26", fr: "la serveuse", de: "die Kellnerin" },
    { id: "r27", fr: "commander", de: "bestellen" },
    { id: "r28", fr: "réserver", de: "reservieren" },
    { id: "r29", fr: "le petit-déjeuner", de: "das Frühstück" },
    { id: "r30", fr: "le déjeuner", de: "das Mittagessen" },
    { id: "r31", fr: "le dîner", de: "das Abendessen" },
    { id: "r32", fr: "un verre de", de: "ein Glas" },
    { id: "r33", fr: "une bouteille de", de: "eine Flasche" },
  ]},
  einkaufen: { name: "Einkaufen", icon: "🛒", level: "A2", words: [
    { id: "e01", fr: "le magasin", de: "das Geschäft" },
    { id: "e02", fr: "le supermarché", de: "der Supermarkt" },
    { id: "e03", fr: "la boulangerie", de: "die Bäckerei" },
    { id: "e04", fr: "la pharmacie", de: "die Apotheke" },
    { id: "e05", fr: "le marché", de: "der Markt" },
    { id: "e06", fr: "acheter", de: "kaufen" },
    { id: "e07", fr: "payer", de: "bezahlen" },
    { id: "e08", fr: "le prix", de: "der Preis" },
    { id: "e09", fr: "combien ça coûte ?", de: "wie viel kostet das?" },
    { id: "e10", fr: "c'est trop cher", de: "das ist zu teuer" },
    { id: "e11", fr: "la caisse", de: "die Kasse" },
    { id: "e12", fr: "le sac", de: "die Tüte" },
    { id: "e13", fr: "la monnaie", de: "das Wechselgeld" },
    { id: "e14", fr: "la carte bancaire", de: "die Bankkarte" },
    { id: "e15", fr: "en espèces", de: "in bar" },
    { id: "e16", fr: "la taille", de: "die Größe" },
    { id: "e17", fr: "essayer", de: "anprobieren" },
    { id: "e18", fr: "la cabine d'essayage", de: "die Umkleidekabine" },
    { id: "e19", fr: "les soldes", de: "der Schlussverkauf" },
    { id: "e20", fr: "une réduction", de: "ein Rabatt" },
    { id: "e21", fr: "ouvert", de: "geöffnet" },
    { id: "e22", fr: "fermé", de: "geschlossen" },
    { id: "e23", fr: "le ticket de caisse", de: "der Kassenbon" },
    { id: "e24", fr: "un kilo de", de: "ein Kilo" },
    { id: "e25", fr: "je cherche...", de: "ich suche..." },
    { id: "e26", fr: "les fruits", de: "das Obst" },
    { id: "e27", fr: "les légumes", de: "das Gemüse" },
    { id: "e28", fr: "le lait", de: "die Milch" },
    { id: "e29", fr: "les oeufs", de: "die Eier" },
    { id: "e30", fr: "le beurre", de: "die Butter" },
  ]},
  wegbeschreibung: { name: "Nach dem Weg fragen", icon: "🗺️", level: "A2", words: [
    { id: "w01", fr: "où est... ?", de: "wo ist...?" },
    { id: "w02", fr: "tout droit", de: "geradeaus" },
    { id: "w03", fr: "à gauche", de: "nach links" },
    { id: "w04", fr: "à droite", de: "nach rechts" },
    { id: "w05", fr: "la rue", de: "die Straße" },
    { id: "w06", fr: "la place", de: "der Platz" },
    { id: "w07", fr: "le carrefour", de: "die Kreuzung" },
    { id: "w08", fr: "le feu rouge", de: "die Ampel" },
    { id: "w09", fr: "le pont", de: "die Brücke" },
    { id: "w10", fr: "la gare", de: "der Bahnhof" },
    { id: "w11", fr: "l'arrêt de bus", de: "die Bushaltestelle" },
    { id: "w12", fr: "le métro", de: "die U-Bahn" },
    { id: "w13", fr: "le plan", de: "der Stadtplan" },
    { id: "w14", fr: "près de", de: "in der Nähe von" },
    { id: "w15", fr: "loin de", de: "weit von" },
    { id: "w16", fr: "en face de", de: "gegenüber von" },
    { id: "w17", fr: "à côté de", de: "neben" },
    { id: "w18", fr: "entre", de: "zwischen" },
    { id: "w19", fr: "derrière", de: "hinter" },
    { id: "w20", fr: "devant", de: "vor" },
    { id: "w21", fr: "tourner", de: "abbiegen" },
    { id: "w22", fr: "continuer", de: "weitergehen" },
    { id: "w23", fr: "traverser", de: "überqueren" },
    { id: "w24", fr: "le coin", de: "die Ecke" },
    { id: "w25", fr: "c'est loin ?", de: "ist es weit?" },
    { id: "w26", fr: "à pied", de: "zu Fuß" },
    { id: "w27", fr: "en voiture", de: "mit dem Auto" },
    { id: "w28", fr: "le taxi", de: "das Taxi" },
    { id: "w29", fr: "le centre-ville", de: "die Innenstadt" },
    { id: "w30", fr: "l'office de tourisme", de: "das Tourismusbüro" },
  ]},
  hotel: { name: "Im Hotel", icon: "🏨", level: "A2", words: [
    { id: "h01", fr: "l'hôtel", de: "das Hotel" },
    { id: "h02", fr: "la chambre", de: "das Zimmer" },
    { id: "h03", fr: "la réservation", de: "die Reservierung" },
    { id: "h04", fr: "la réception", de: "die Rezeption" },
    { id: "h05", fr: "la clé", de: "der Schlüssel" },
    { id: "h06", fr: "une chambre simple", de: "ein Einzelzimmer" },
    { id: "h07", fr: "une chambre double", de: "ein Doppelzimmer" },
    { id: "h08", fr: "le lit", de: "das Bett" },
    { id: "h09", fr: "la salle de bain", de: "das Badezimmer" },
    { id: "h10", fr: "la douche", de: "die Dusche" },
    { id: "h11", fr: "la serviette", de: "das Handtuch" },
    { id: "h12", fr: "l'ascenseur", de: "der Aufzug" },
    { id: "h13", fr: "le rez-de-chaussée", de: "das Erdgeschoss" },
    { id: "h14", fr: "l'étage", de: "das Stockwerk" },
    { id: "h15", fr: "la vue", de: "die Aussicht" },
    { id: "h16", fr: "le balcon", de: "der Balkon" },
    { id: "h17", fr: "la piscine", de: "der Pool" },
    { id: "h18", fr: "le parking", de: "der Parkplatz" },
    { id: "h19", fr: "le Wi-Fi", de: "das WLAN" },
    { id: "h20", fr: "la nuit", de: "die Nacht" },
    { id: "h21", fr: "arriver", de: "ankommen" },
    { id: "h22", fr: "partir", de: "abreisen" },
    { id: "h23", fr: "la valise", de: "der Koffer" },
    { id: "h24", fr: "le passeport", de: "der Reisepass" },
    { id: "h25", fr: "la climatisation", de: "die Klimaanlage" },
    { id: "h26", fr: "le chauffage", de: "die Heizung" },
    { id: "h27", fr: "le petit-déjeuner inclus", de: "Frühstück inklusive" },
    { id: "h28", fr: "complet", de: "ausgebucht" },
    { id: "h29", fr: "disponible", de: "verfügbar" },
    { id: "h30", fr: "la carte d'identité", de: "der Personalausweis" },
  ]},
  strand: { name: "Am Strand & Freizeit", icon: "🏖️", level: "A2", words: [
    { id: "s01", fr: "la plage", de: "der Strand" },
    { id: "s02", fr: "la mer", de: "das Meer" },
    { id: "s03", fr: "le soleil", de: "die Sonne" },
    { id: "s04", fr: "la crème solaire", de: "die Sonnencreme" },
    { id: "s05", fr: "les lunettes de soleil", de: "die Sonnenbrille" },
    { id: "s06", fr: "le maillot de bain", de: "der Badeanzug" },
    { id: "s07", fr: "la serviette de plage", de: "das Strandtuch" },
    { id: "s08", fr: "nager", de: "schwimmen" },
    { id: "s09", fr: "se baigner", de: "baden" },
    { id: "s10", fr: "le sable", de: "der Sand" },
    { id: "s11", fr: "les vagues", de: "die Wellen" },
    { id: "s12", fr: "le parasol", de: "der Sonnenschirm" },
    { id: "s13", fr: "la glace", de: "das Eis" },
    { id: "s14", fr: "le vélo", de: "das Fahrrad" },
    { id: "s15", fr: "la promenade", de: "der Spaziergang" },
    { id: "s16", fr: "se promener", de: "spazieren gehen" },
    { id: "s17", fr: "le musée", de: "das Museum" },
    { id: "s18", fr: "le cinéma", de: "das Kino" },
    { id: "s19", fr: "le parc", de: "der Park" },
    { id: "s20", fr: "la montagne", de: "der Berg" },
    { id: "s21", fr: "le lac", de: "der See" },
    { id: "s22", fr: "la forêt", de: "der Wald" },
    { id: "s23", fr: "la randonnée", de: "die Wanderung" },
    { id: "s24", fr: "le coucher de soleil", de: "der Sonnenuntergang" },
    { id: "s25", fr: "les vacances", de: "der Urlaub" },
    { id: "s26", fr: "se reposer", de: "sich ausruhen" },
    { id: "s27", fr: "bronzer", de: "sich sonnen" },
    { id: "s28", fr: "la carte postale", de: "die Postkarte" },
    { id: "s29", fr: "le souvenir", de: "das Andenken" },
    { id: "s30", fr: "profiter de", de: "genießen" },
  ]},
  zahlen: { name: "Zahlen & Uhrzeit", icon: "🔢", level: "A1", words: [
    { id: "z01", fr: "zéro", de: "null" },
    { id: "z02", fr: "un", de: "eins" },
    { id: "z03", fr: "deux", de: "zwei" },
    { id: "z04", fr: "trois", de: "drei" },
    { id: "z05", fr: "quatre", de: "vier" },
    { id: "z06", fr: "cinq", de: "fünf" },
    { id: "z07", fr: "six", de: "sechs" },
    { id: "z08", fr: "sept", de: "sieben" },
    { id: "z09", fr: "huit", de: "acht" },
    { id: "z10", fr: "neuf", de: "neun" },
    { id: "z11", fr: "dix", de: "zehn" },
    { id: "z12", fr: "vingt", de: "zwanzig" },
    { id: "z13", fr: "trente", de: "dreißig" },
    { id: "z14", fr: "quarante", de: "vierzig" },
    { id: "z15", fr: "cinquante", de: "fünfzig" },
    { id: "z16", fr: "soixante", de: "sechzig" },
    { id: "z17", fr: "soixante-dix", de: "siebzig" },
    { id: "z18", fr: "quatre-vingts", de: "achtzig" },
    { id: "z19", fr: "quatre-vingt-dix", de: "neunzig" },
    { id: "z20", fr: "cent", de: "hundert" },
    { id: "z21", fr: "mille", de: "tausend" },
    { id: "z22", fr: "quelle heure est-il ?", de: "wie spät ist es?" },
    { id: "z23", fr: "il est ... heures", de: "es ist ... Uhr" },
    { id: "z24", fr: "midi", de: "Mittag" },
    { id: "z25", fr: "minuit", de: "Mitternacht" },
    { id: "z26", fr: "et quart", de: "Viertel nach" },
    { id: "z27", fr: "et demie", de: "halb" },
    { id: "z28", fr: "moins le quart", de: "Viertel vor" },
    { id: "z29", fr: "le matin", de: "der Morgen" },
    { id: "z30", fr: "l'après-midi", de: "der Nachmittag" },
    { id: "z31", fr: "le soir", de: "der Abend" },
    { id: "z32", fr: "aujourd'hui", de: "heute" },
    { id: "z33", fr: "demain", de: "morgen" },
    { id: "z34", fr: "hier", de: "gestern" },
    { id: "z35", fr: "la semaine", de: "die Woche" },
  ]},
  alltag: { name: "Alltag", icon: "🏠", level: "A2", words: [
    { id: "a01", fr: "la maison", de: "das Haus" },
    { id: "a02", fr: "la famille", de: "die Familie" },
    { id: "a03", fr: "le père", de: "der Vater" },
    { id: "a04", fr: "la mère", de: "die Mutter" },
    { id: "a05", fr: "le frère", de: "der Bruder" },
    { id: "a06", fr: "la soeur", de: "die Schwester" },
    { id: "a07", fr: "les enfants", de: "die Kinder" },
    { id: "a08", fr: "le temps", de: "das Wetter" },
    { id: "a09", fr: "il fait beau", de: "es ist schön" },
    { id: "a10", fr: "il fait chaud", de: "es ist warm" },
    { id: "a11", fr: "il fait froid", de: "es ist kalt" },
    { id: "a12", fr: "il pleut", de: "es regnet" },
    { id: "a13", fr: "il neige", de: "es schneit" },
    { id: "a14", fr: "le nuage", de: "die Wolke" },
    { id: "a15", fr: "le vent", de: "der Wind" },
    { id: "a16", fr: "la tête", de: "der Kopf" },
    { id: "a17", fr: "le bras", de: "der Arm" },
    { id: "a18", fr: "la jambe", de: "das Bein" },
    { id: "a19", fr: "le dos", de: "der Rücken" },
    { id: "a20", fr: "le ventre", de: "der Bauch" },
    { id: "a21", fr: "le pantalon", de: "die Hose" },
    { id: "a22", fr: "la robe", de: "das Kleid" },
    { id: "a23", fr: "la chemise", de: "das Hemd" },
    { id: "a24", fr: "les chaussures", de: "die Schuhe" },
    { id: "a25", fr: "le manteau", de: "der Mantel" },
    { id: "a26", fr: "le chapeau", de: "der Hut" },
    { id: "a27", fr: "le chien", de: "der Hund" },
    { id: "a28", fr: "le chat", de: "die Katze" },
    { id: "a29", fr: "aimer", de: "lieben / mögen" },
    { id: "a30", fr: "manger", de: "essen" },
    { id: "a31", fr: "boire", de: "trinken" },
    { id: "a32", fr: "dormir", de: "schlafen" },
    { id: "a33", fr: "parler", de: "sprechen" },
    { id: "a34", fr: "écouter", de: "zuhören" },
    { id: "a35", fr: "regarder", de: "anschauen" },
  ]},
  notfall: { name: "Notfälle & Arztbesuch", icon: "🚑", level: "B1", words: [
    { id: "n01", fr: "au secours !", de: "Hilfe!" },
    { id: "n02", fr: "appelez la police !", de: "rufen Sie die Polizei!" },
    { id: "n03", fr: "appelez une ambulance !", de: "rufen Sie einen Krankenwagen!" },
    { id: "n04", fr: "le médecin", de: "der Arzt" },
    { id: "n05", fr: "l'hôpital", de: "das Krankenhaus" },
    { id: "n06", fr: "la pharmacie", de: "die Apotheke" },
    { id: "n07", fr: "j'ai mal à...", de: "mir tut ... weh" },
    { id: "n08", fr: "j'ai mal à la tête", de: "ich habe Kopfschmerzen" },
    { id: "n09", fr: "j'ai mal au ventre", de: "ich habe Bauchschmerzen" },
    { id: "n10", fr: "j'ai de la fièvre", de: "ich habe Fieber" },
    { id: "n11", fr: "je suis malade", de: "ich bin krank" },
    { id: "n12", fr: "je suis allergique à...", de: "ich bin allergisch gegen..." },
    { id: "n13", fr: "le médicament", de: "das Medikament" },
    { id: "n14", fr: "l'ordonnance", de: "das Rezept" },
    { id: "n15", fr: "la douleur", de: "der Schmerz" },
    { id: "n16", fr: "le dentiste", de: "der Zahnarzt" },
    { id: "n17", fr: "les urgences", de: "die Notaufnahme" },
    { id: "n18", fr: "le pompier", de: "der Feuerwehrmann" },
    { id: "n19", fr: "la police", de: "die Polizei" },
    { id: "n20", fr: "j'ai perdu...", de: "ich habe ... verloren" },
    { id: "n21", fr: "on m'a volé...", de: "man hat mir ... gestohlen" },
    { id: "n22", fr: "le portefeuille", de: "die Geldbörse" },
    { id: "n23", fr: "le téléphone", de: "das Telefon" },
    { id: "n24", fr: "l'assurance", de: "die Versicherung" },
    { id: "n25", fr: "le numéro d'urgence", de: "die Notrufnummer" },
    { id: "n26", fr: "c'est urgent", de: "es ist dringend" },
    { id: "n27", fr: "aidez-moi", de: "helfen Sie mir" },
    { id: "n28", fr: "je ne me sens pas bien", de: "mir geht es nicht gut" },
    { id: "n29", fr: "la piqûre", de: "die Spritze" },
    { id: "n30", fr: "le pansement", de: "das Pflaster" },
  ]},
  transport: { name: "Reisen & Transport", icon: "✈️", level: "B1", words: [
    { id: "t01", fr: "l'aéroport", de: "der Flughafen" },
    { id: "t02", fr: "le vol", de: "der Flug" },
    { id: "t03", fr: "le billet", de: "das Ticket" },
    { id: "t04", fr: "le billet aller-retour", de: "die Hin- und Rückfahrkarte" },
    { id: "t05", fr: "l'aller simple", de: "die einfache Fahrt" },
    { id: "t06", fr: "le départ", de: "die Abfahrt / der Abflug" },
    { id: "t07", fr: "l'arrivée", de: "die Ankunft" },
    { id: "t08", fr: "le retard", de: "die Verspätung" },
    { id: "t09", fr: "la correspondance", de: "der Anschluss (Verbindung)" },
    { id: "t10", fr: "la salle d'attente", de: "der Wartesaal" },
    { id: "t11", fr: "le quai", de: "der Bahnsteig" },
    { id: "t12", fr: "la voie", de: "das Gleis" },
    { id: "t13", fr: "le guichet", de: "der Schalter" },
    { id: "t14", fr: "la carte d'embarquement", de: "die Bordkarte" },
    { id: "t15", fr: "le bagage à main", de: "das Handgepäck" },
    { id: "t16", fr: "le bagage enregistré", de: "das aufgegebene Gepäck" },
    { id: "t17", fr: "la consigne", de: "die Gepäckaufbewahrung" },
    { id: "t18", fr: "la douane", de: "der Zoll" },
    { id: "t19", fr: "la frontière", de: "die Grenze" },
    { id: "t20", fr: "la location de voiture", de: "die Autovermietung" },
    { id: "t21", fr: "l'assurance voyage", de: "die Reiseversicherung" },
    { id: "t22", fr: "embarquer", de: "einsteigen / an Bord gehen" },
    { id: "t23", fr: "débarquer", de: "aussteigen / von Bord gehen" },
    { id: "t24", fr: "annuler", de: "stornieren" },
    { id: "t25", fr: "rembourser", de: "zurückerstatten" },
    { id: "t26", fr: "l'hôtesse de l'air", de: "die Stewardess" },
    { id: "t27", fr: "le pilote", de: "der Pilot" },
    { id: "t28", fr: "le contrôle des passeports", de: "die Passkontrolle" },
    { id: "t29", fr: "enregistrer les bagages", de: "Gepäck aufgeben" },
    { id: "t30", fr: "manquer le train", de: "den Zug verpassen" },
  ]},
  arbeit: { name: "Arbeit & Wirtschaft", icon: "💼", level: "B2", words: [
    { id: "ar01", fr: "l'entreprise", de: "das Unternehmen" },
    { id: "ar02", fr: "l'employé(e)", de: "der/die Angestellte" },
    { id: "ar03", fr: "le patron / la patronne", de: "der Chef / die Chefin" },
    { id: "ar04", fr: "le contrat", de: "der Vertrag" },
    { id: "ar05", fr: "le salaire", de: "das Gehalt" },
    { id: "ar06", fr: "la réunion", de: "die Besprechung" },
    { id: "ar07", fr: "le chômage", de: "die Arbeitslosigkeit" },
    { id: "ar08", fr: "la formation", de: "die Ausbildung / Weiterbildung" },
    { id: "ar09", fr: "l'entretien d'embauche", de: "das Vorstellungsgespräch" },
    { id: "ar10", fr: "le curriculum vitae", de: "der Lebenslauf" },
    { id: "ar11", fr: "la candidature", de: "die Bewerbung" },
    { id: "ar12", fr: "le poste", de: "die Stelle" },
    { id: "ar13", fr: "démissionner", de: "kündigen" },
    { id: "ar14", fr: "licencier", de: "entlassen" },
    { id: "ar15", fr: "embaucher", de: "einstellen" },
    { id: "ar16", fr: "la retraite", de: "die Rente / der Ruhestand" },
    { id: "ar17", fr: "les congés payés", de: "der bezahlte Urlaub" },
    { id: "ar18", fr: "les heures supplémentaires", de: "die Überstunden" },
    { id: "ar19", fr: "le syndicat", de: "die Gewerkschaft" },
    { id: "ar20", fr: "la grève", de: "der Streik" },
    { id: "ar21", fr: "le bénéfice", de: "der Gewinn" },
    { id: "ar22", fr: "la perte", de: "der Verlust" },
    { id: "ar23", fr: "l'investissement", de: "die Investition" },
    { id: "ar24", fr: "la concurrence", de: "die Konkurrenz" },
    { id: "ar25", fr: "le budget", de: "das Budget" },
    { id: "ar26", fr: "le projet", de: "das Projekt" },
    { id: "ar27", fr: "la réussite", de: "der Erfolg" },
    { id: "ar28", fr: "le marché du travail", de: "der Arbeitsmarkt" },
    { id: "ar29", fr: "les charges sociales", de: "die Sozialabgaben" },
    { id: "ar30", fr: "le télétravail", de: "das Homeoffice" },
  ]},
  gesellschaft: { name: "Gesellschaft & Medien", icon: "📰", level: "B2", words: [
    { id: "g01", fr: "les élections", de: "die Wahlen" },
    { id: "g02", fr: "le gouvernement", de: "die Regierung" },
    { id: "g03", fr: "le maire", de: "der Bürgermeister" },
    { id: "g04", fr: "le président", de: "der Präsident" },
    { id: "g05", fr: "la loi", de: "das Gesetz" },
    { id: "g06", fr: "les impôts", de: "die Steuern" },
    { id: "g07", fr: "la manifestation", de: "die Demonstration" },
    { id: "g08", fr: "les réseaux sociaux", de: "die sozialen Medien" },
    { id: "g09", fr: "le journal", de: "die Zeitung" },
    { id: "g10", fr: "la chaîne de télévision", de: "der Fernsehsender" },
    { id: "g11", fr: "la publicité", de: "die Werbung" },
    { id: "g12", fr: "l'opinion publique", de: "die öffentliche Meinung" },
    { id: "g13", fr: "le débat", de: "die Debatte" },
    { id: "g14", fr: "la polémique", de: "die Kontroverse" },
    { id: "g15", fr: "la solidarité", de: "die Solidarität" },
    { id: "g16", fr: "l'égalité", de: "die Gleichheit" },
    { id: "g17", fr: "la liberté", de: "die Freiheit" },
    { id: "g18", fr: "la pauvreté", de: "die Armut" },
    { id: "g19", fr: "la richesse", de: "der Reichtum" },
    { id: "g20", fr: "la discrimination", de: "die Diskriminierung" },
    { id: "g21", fr: "les droits de l'homme", de: "die Menschenrechte" },
    { id: "g22", fr: "la santé publique", de: "die öffentliche Gesundheit" },
    { id: "g23", fr: "le bénévole", de: "der/die Freiwillige" },
    { id: "g24", fr: "l'association", de: "der Verein" },
    { id: "g25", fr: "la citoyenneté", de: "die Staatsbürgerschaft" },
    { id: "g26", fr: "le vote", de: "die Abstimmung / die Wahl" },
    { id: "g27", fr: "le changement climatique", de: "der Klimawandel" },
    { id: "g28", fr: "l'intégration", de: "die Integration" },
    { id: "g29", fr: "la laïcité", de: "die Laizität (Trennung Kirche/Staat)" },
    { id: "g30", fr: "la démocratie", de: "die Demokratie" },
  ]},
  gefuehle: { name: "Gefühle & Psychologie", icon: "🧠", level: "C1", words: [
    { id: "gf01", fr: "la nostalgie", de: "die Nostalgie / Sehnsucht" },
    { id: "gf02", fr: "l'anxiété", de: "die Angst / Angststörung" },
    { id: "gf03", fr: "la mélancolie", de: "die Melancholie" },
    { id: "gf04", fr: "la jalousie", de: "die Eifersucht" },
    { id: "gf05", fr: "la fierté", de: "der Stolz" },
    { id: "gf06", fr: "la honte", de: "die Scham" },
    { id: "gf07", fr: "le remords", de: "die Reue" },
    { id: "gf08", fr: "l'espoir", de: "die Hoffnung" },
    { id: "gf09", fr: "la déception", de: "die Enttäuschung" },
    { id: "gf10", fr: "la confiance", de: "das Vertrauen" },
    { id: "gf11", fr: "la méfiance", de: "das Misstrauen" },
    { id: "gf12", fr: "l'empathie", de: "die Empathie" },
    { id: "gf13", fr: "surmonter", de: "überwinden" },
    { id: "gf14", fr: "ressentir", de: "empfinden / fühlen" },
    { id: "gf15", fr: "exprimer", de: "ausdrücken" },
    { id: "gf16", fr: "refouler", de: "unterdrücken (Gefühle)" },
    { id: "gf17", fr: "épanouissant(e)", de: "erfüllend" },
    { id: "gf18", fr: "bouleversé(e)", de: "erschüttert / aufgewühlt" },
    { id: "gf19", fr: "apaisé(e)", de: "beruhigt" },
    { id: "gf20", fr: "soulagé(e)", de: "erleichtert" },
    { id: "gf21", fr: "angoissé(e)", de: "verängstigt / angespannt" },
    { id: "gf22", fr: "déprimé(e)", de: "deprimiert" },
    { id: "gf23", fr: "épuisé(e)", de: "erschöpft" },
    { id: "gf24", fr: "le bien-être", de: "das Wohlbefinden" },
    { id: "gf25", fr: "la résilience", de: "die Resilienz" },
    { id: "gf26", fr: "le traumatisme", de: "das Trauma" },
    { id: "gf27", fr: "la thérapie", de: "die Therapie" },
    { id: "gf28", fr: "le comportement", de: "das Verhalten" },
    { id: "gf29", fr: "l'inconscient", de: "das Unbewusste" },
    { id: "gf30", fr: "se réconcilier", de: "sich versöhnen" },
  ]},
  umwelt: { name: "Natur & Umwelt", icon: "🌿", level: "C1", words: [
    { id: "u01", fr: "la biodiversité", de: "die Biodiversität" },
    { id: "u02", fr: "l'espèce menacée", de: "die bedrohte Art" },
    { id: "u03", fr: "la déforestation", de: "die Entwaldung" },
    { id: "u04", fr: "le développement durable", de: "die nachhaltige Entwicklung" },
    { id: "u05", fr: "les énergies renouvelables", de: "erneuerbare Energien" },
    { id: "u06", fr: "le réchauffement climatique", de: "die Erderwärmung" },
    { id: "u07", fr: "la pollution", de: "die Umweltverschmutzung" },
    { id: "u08", fr: "la sécheresse", de: "die Dürre" },
    { id: "u09", fr: "l'inondation", de: "die Überschwemmung" },
    { id: "u10", fr: "le tremblement de terre", de: "das Erdbeben" },
    { id: "u11", fr: "l'ouragan", de: "der Orkan / Hurrikan" },
    { id: "u12", fr: "le glacier", de: "der Gletscher" },
    { id: "u13", fr: "la fonte des glaces", de: "das Abschmelzen des Eises" },
    { id: "u14", fr: "l'empreinte carbone", de: "der CO2-Fußabdruck" },
    { id: "u15", fr: "recycler", de: "recyceln" },
    { id: "u16", fr: "préserver", de: "bewahren / erhalten" },
    { id: "u17", fr: "sensibiliser", de: "sensibilisieren" },
    { id: "u18", fr: "l'écosystème", de: "das Ökosystem" },
    { id: "u19", fr: "la faune", de: "die Tierwelt" },
    { id: "u20", fr: "la flore", de: "die Pflanzenwelt" },
    { id: "u21", fr: "l'agriculture biologique", de: "biologische Landwirtschaft" },
    { id: "u22", fr: "les pesticides", de: "die Pestizide" },
    { id: "u23", fr: "l'eau douce", de: "das Süßwasser" },
    { id: "u24", fr: "l'extinction", de: "das Aussterben" },
    { id: "u25", fr: "la nature sauvage", de: "die Wildnis" },
    { id: "u26", fr: "le paysage", de: "die Landschaft" },
    { id: "u27", fr: "l'habitat naturel", de: "der natürliche Lebensraum" },
    { id: "u28", fr: "la conscience écologique", de: "das Umweltbewusstsein" },
    { id: "u29", fr: "la marée noire", de: "die Ölpest" },
    { id: "u30", fr: "zéro déchet", de: "Null Abfall / Zero Waste" },
  ]},
  redewendungen: { name: "Redewendungen & Idiome", icon: "💬", level: "C2", words: [
    { id: "rw01", fr: "avoir le cafard", de: "Trübsal blasen (wörtl.: eine Kakerlake haben)" },
    { id: "rw02", fr: "poser un lapin", de: "jdn versetzen (wörtl.: ein Kaninchen hinlegen)" },
    { id: "rw03", fr: "tomber dans les pommes", de: "ohnmächtig werden (wörtl.: in die Äpfel fallen)" },
    { id: "rw04", fr: "casser les pieds", de: "nerven (wörtl.: die Füße brechen)" },
    { id: "rw05", fr: "avoir le coup de foudre", de: "sich verlieben (wörtl.: einen Blitzschlag haben)" },
    { id: "rw06", fr: "mieux vaut tard que jamais", de: "besser spät als nie" },
    { id: "rw07", fr: "les bras m'en tombent", de: "ich bin sprachlos (wörtl.: mir fallen die Arme runter)" },
    { id: "rw08", fr: "coûter les yeux de la tête", de: "ein Vermögen kosten" },
    { id: "rw09", fr: "avoir du pain sur la planche", de: "viel zu tun haben" },
    { id: "rw10", fr: "se noyer dans un verre d'eau", de: "aus einer Mücke einen Elefanten machen" },
    { id: "rw11", fr: "pleuvoir des cordes", de: "in Strömen regnen" },
    { id: "rw12", fr: "prendre ses jambes à son cou", de: "Reißaus nehmen" },
    { id: "rw13", fr: "avoir d'autres chats à fouetter", de: "Wichtigeres zu tun haben" },
    { id: "rw14", fr: "mettre les pieds dans le plat", de: "ins Fettnäpfchen treten" },
    { id: "rw15", fr: "avoir le vent en poupe", de: "Rückenwind haben / erfolgreich sein" },
    { id: "rw16", fr: "brûler la chandelle par les deux bouts", de: "die Kerze von beiden Enden anzünden" },
    { id: "rw17", fr: "jeter de l'huile sur le feu", de: "Öl ins Feuer gießen" },
    { id: "rw18", fr: "garder la tête hors de l'eau", de: "sich über Wasser halten" },
    { id: "rw19", fr: "faire d'une pierre deux coups", de: "zwei Fliegen mit einer Klappe schlagen" },
    { id: "rw20", fr: "mettre de l'eau dans son vin", de: "Wasser in den Wein gießen / zurückstecken" },
    { id: "rw21", fr: "rompre la glace", de: "das Eis brechen" },
    { id: "rw22", fr: "tourner autour du pot", de: "wie die Katze um den heißen Brei gehen" },
    { id: "rw23", fr: "avoir la tête dans les nuages", de: "in den Wolken schweben / träumen" },
    { id: "rw24", fr: "tenir la route", de: "standhalten / funktionieren" },
    { id: "rw25", fr: "casser sa pipe", de: "sterben (umgangssprachlich)" },
    { id: "rw26", fr: "ne pas y aller de main morte", de: "nicht zimperlich sein / kräftig zuschlagen" },
    { id: "rw27", fr: "avoir le beurre et l'argent du beurre", de: "den Kuchen essen und behalten wollen" },
    { id: "rw28", fr: "c'est bonnet blanc et blanc bonnet", de: "das ist Jacke wie Hose" },
    { id: "rw29", fr: "chercher midi à quatorze heures", de: "unnötig komplizieren" },
    { id: "rw30", fr: "il ne faut pas vendre la peau de l'ours avant de l'avoir tué", de: "man soll den Tag nicht vor dem Abend loben" },
  ]}
};

const EINSTUFUNG_FRAGEN = [
  { frage: "Wie sagt man 'Guten Tag' auf Französisch?", optionen: ["Bonjour", "Bonsoir", "Salut", "Merci"], antwort: 0, level: "A1" },
  { frage: "Was bedeutet 'merci'?", optionen: ["bitte", "danke", "hallo", "tschüss"], antwort: 1, level: "A1" },
  { frage: "Welches Wort bedeutet 'ja'?", optionen: ["non", "oui", "bien", "mal"], antwort: 1, level: "A1" },
  { frage: "'Le pain' bedeutet...?", optionen: ["der Wein", "der Käse", "das Brot", "das Wasser"], antwort: 2, level: "A1" },
  { frage: "'Ich heiße...' auf Französisch?", optionen: ["je suis...", "je m'appelle...", "j'ai...", "je vais..."], antwort: 1, level: "A1" },
  { frage: "'Das Wasser' auf Französisch?", optionen: ["le vin", "le lait", "l'eau", "le jus"], antwort: 2, level: "A1" },
  { frage: "'Trois' bedeutet...?", optionen: ["zwei", "drei", "vier", "fünf"], antwort: 1, level: "A1" },
  { frage: "'Au revoir' bedeutet...?", optionen: ["guten Tag", "guten Abend", "auf Wiedersehen", "willkommen"], antwort: 2, level: "A1" },
  { frage: "'Ich hätte gern einen Kaffee' auf Französisch?", optionen: ["Je veux un café", "Je voudrais un café", "Je prends un café", "Je bois un café"], antwort: 1, level: "A2" },
  { frage: "'Wie viel kostet das?' auf Französisch?", optionen: ["C'est combien ?", "Combien ça coûte ?", "Quel prix ?", "C'est cher ?"], antwort: 1, level: "A2" },
  { frage: "Welcher Artikel passt? __ maison", optionen: ["le", "la", "les", "un"], antwort: 1, level: "A2" },
  { frage: "'Je suis allé au marché' — welche Zeitform?", optionen: ["Présent", "Imparfait", "Passé composé", "Futur"], antwort: 2, level: "A2" },
  { frage: "'À gauche' bedeutet...?", optionen: ["nach rechts", "nach links", "geradeaus", "zurück"], antwort: 1, level: "A2" },
  { frage: "Wie bildet man die Verneinung von 'Je sais'?", optionen: ["Je sais non", "Je ne sais pas", "Je pas sais", "Ne je sais"], antwort: 1, level: "A2" },
  { frage: "'Quatre-vingts' ist welche Zahl?", optionen: ["40", "60", "80", "90"], antwort: 2, level: "A2" },
  { frage: "Welche Form ist Conditionnel von 'manger' (je)?", optionen: ["je mange", "je mangeais", "je mangerais", "je mangerai"], antwort: 2, level: "B1" },
  { frage: "Si j'avais le temps, je __ au cinéma.", optionen: ["vais", "allais", "irai", "irais"], antwort: 3, level: "B1" },
  { frage: "'Il faut que tu partes' bedeutet...?", optionen: ["Du kannst gehen", "Du musst gehen", "Du willst gehen", "Du gehst"], antwort: 1, level: "B1" },
  { frage: "Wie ersetzt man 'les livres' durch ein Pronomen?", optionen: ["leur", "les", "en", "y"], antwort: 1, level: "B1" },
  { frage: "'Bien que' verlangt welchen Modus?", optionen: ["Indicatif", "Conditionnel", "Subjonctif", "Impératif"], antwort: 2, level: "B1" },
];
