const VOKABELN = {
  begruessung: { name: "Begrüßung & Höflichkeit", icon: "👋", level: "A1", words: [
    { id: "b01", fr: "bonjour", de: "guten Tag" },
    { id: "b02", fr: "bonsoir", de: "guten Abend" },
    { id: "b03", fr: "bonne nuit", de: "gute Nacht" },
    { id: "b04", fr: "au revoir", de: "auf Wiedersehen" },
    { id: "b05", fr: "salut", de: "hallo / tschüss" },
    { id: "b06", fr: "merci", de: "danke" },
    { id: "b07", fr: "merci beaucoup", de: "vielen Dank" },
    { id: "b08", fr: "s'il vous plaît", de: "bitte (höflich)" },
    { id: "b09", fr: "s'il te plaît", de: "bitte (vertraut)" },
    { id: "b10", fr: "de rien", de: "gern geschehen" },
    { id: "b11", fr: "excusez-moi", de: "entschuldigen Sie" },
    { id: "b12", fr: "pardon", de: "Verzeihung" },
    { id: "b13", fr: "oui", de: "ja" },
    { id: "b14", fr: "non", de: "nein" },
    { id: "b15", fr: "comment allez-vous ?", de: "wie geht es Ihnen?" },
    { id: "b16", fr: "ça va ?", de: "wie geht's?" },
    { id: "b17", fr: "ça va bien", de: "mir geht es gut" },
    { id: "b18", fr: "je m'appelle...", de: "ich heiße..." },
    { id: "b19", fr: "enchanté(e)", de: "freut mich" },
    { id: "b20", fr: "à bientôt", de: "bis bald" },
    { id: "b21", fr: "à demain", de: "bis morgen" },
    { id: "b22", fr: "bienvenue", de: "willkommen" },
    { id: "b23", fr: "madame", de: "Frau" },
    { id: "b24", fr: "monsieur", de: "Herr" },
    { id: "b25", fr: "je suis désolé(e)", de: "es tut mir leid" },
    { id: "b26", fr: "bonne journée", de: "schönen Tag" },
    { id: "b27", fr: "avec plaisir", de: "mit Vergnügen" },
    { id: "b28", fr: "d'accord", de: "einverstanden" },
    { id: "b29", fr: "bien sûr", de: "natürlich" },
    { id: "b30", fr: "je ne comprends pas", de: "ich verstehe nicht" },
  ]},
  restaurant: { name: "Im Restaurant", icon: "🍽️", level: "A1", words: [
    { id: "r01", fr: "le restaurant", de: "das Restaurant" },
    { id: "r02", fr: "la carte", de: "die Speisekarte" },
    { id: "r03", fr: "le menu", de: "das Menü" },
    { id: "r04", fr: "l'entrée", de: "die Vorspeise" },
    { id: "r05", fr: "le plat principal", de: "das Hauptgericht" },
    { id: "r06", fr: "le dessert", de: "der Nachtisch" },
    { id: "r07", fr: "la boisson", de: "das Getränk" },
    { id: "r08", fr: "l'eau", de: "das Wasser" },
    { id: "r09", fr: "le vin", de: "der Wein" },
    { id: "r10", fr: "la bière", de: "das Bier" },
    { id: "r11", fr: "le café", de: "der Kaffee" },
    { id: "r12", fr: "le thé", de: "der Tee" },
    { id: "r13", fr: "le pain", de: "das Brot" },
    { id: "r14", fr: "le fromage", de: "der Käse" },
    { id: "r15", fr: "la viande", de: "das Fleisch" },
    { id: "r16", fr: "le poisson", de: "der Fisch" },
    { id: "r17", fr: "la salade", de: "der Salat" },
    { id: "r18", fr: "la soupe", de: "die Suppe" },
    { id: "r19", fr: "l'addition", de: "die Rechnung" },
    { id: "r20", fr: "le pourboire", de: "das Trinkgeld" },
    { id: "r21", fr: "une table pour deux", de: "ein Tisch für zwei" },
    { id: "r22", fr: "je voudrais...", de: "ich hätte gern..." },
    { id: "r23", fr: "l'addition, s'il vous plaît", de: "die Rechnung, bitte" },
    { id: "r24", fr: "c'est délicieux", de: "das ist köstlich" },
    { id: "r25", fr: "le serveur", de: "der Kellner" },
    { id: "r26", fr: "la serveuse", de: "die Kellnerin" },
    { id: "r27", fr: "commander", de: "bestellen" },
    { id: "r28", fr: "réserver", de: "reservieren" },
    { id: "r29", fr: "le petit-déjeuner", de: "das Frühstück" },
    { id: "r30", fr: "le déjeuner", de: "das Mittagessen" },
    { id: "r31", fr: "le dîner", de: "das Abendessen" },
    { id: "r32", fr: "un verre de", de: "ein Glas" },
    { id: "r33", fr: "une bouteille de", de: "eine Flasche" },
  ]},
  einkaufen: { name: "Einkaufen", icon: "🛒", level: "A2", words: [
    { id: "e01", fr: "le magasin", de: "das Geschäft" },
    { id: "e02", fr: "le supermarché", de: "der Supermarkt" },
    { id: "e03", fr: "la boulangerie", de: "die Bäckerei" },
    { id: "e04", fr: "la pharmacie", de: "die Apotheke" },
    { id: "e05", fr: "le marché", de: "der Markt" },
    { id: "e06", fr: "acheter", de: "kaufen" },
    { id: "e07", fr: "payer", de: "bezahlen" },
    { id: "e08", fr: "le prix", de: "der Preis" },
    { id: "e09", fr: "combien ça coûte ?", de: "wie viel kostet das?" },
    { id: "e10", fr: "c'est trop cher", de: "das ist zu teuer" },
    { id: "e11", fr: "la caisse", de: "die Kasse" },
    { id: "e12", fr: "le sac", de: "die Tüte" },
    { id: "e13", fr: "la monnaie", de: "das Wechselgeld" },
    { id: "e14", fr: "la carte bancaire", de: "die Bankkarte" },
    { id: "e15", fr: "en espèces", de: "in bar" },
    { id: "e16", fr: "la taille", de: "die Größe" },
    { id: "e17", fr: "essayer", de: "anprobieren" },
    { id: "e18", fr: "la cabine d'essayage", de: "die Umkleidekabine" },
    { id: "e19", fr: "les soldes", de: "der Schlussverkauf" },
    { id: "e20", fr: "une réduction", de: "ein Rabatt" },
    { id: "e21", fr: "ouvert", de: "geöffnet" },
    { id: "e22", fr: "fermé", de: "geschlossen" },
    { id: "e23", fr: "le ticket de caisse", de: "der Kassenbon" },
    { id: "e24", fr: "un kilo de", de: "ein Kilo" },
    { id: "e25", fr: "je cherche...", de: "ich suche..." },
    { id: "e26", fr: "les fruits", de: "das Obst" },
    { id: "e27", fr: "les légumes", de: "das Gemüse" },
    { id: "e28", fr: "le lait", de: "die Milch" },
    { id: "e29", fr: "les oeufs", de: "die Eier" },
    { id: "e30", fr: "le beurre", de: "die Butter" },
  ]},
  wegbeschreibung: { name: "Nach dem Weg fragen", icon: "🗺️", level: "A2", words: [
    { id: "w01", fr: "où est... ?", de: "wo ist...?" },
    { id: "w02", fr: "tout droit", de: "geradeaus" },
    { id: "w03", fr: "à gauche", de: "nach links" },
    { id: "w04", fr: "à droite", de: "nach rechts" },
    { id: "w05", fr: "la rue", de: "die Straße" },
    { id: "w06", fr: "la place", de: "der Platz" },
    { id: "w07", fr: "le carrefour", de: "die Kreuzung" },
    { id: "w08", fr: "le feu rouge", de: "die Ampel" },
    { id: "w09", fr: "le pont", de: "die Brücke" },
    { id: "w10", fr: "la gare", de: "der Bahnhof" },
    { id: "w11", fr: "l'arrêt de bus", de: "die Bushaltestelle" },
    { id: "w12", fr: "le métro", de: "die U-Bahn" },
    { id: "w13", fr: "le plan", de: "der Stadtplan" },
    { id: "w14", fr: "près de", de: "in der Nähe von" },
    { id: "w15", fr: "loin de", de: "weit von" },
    { id: "w16", fr: "en face de", de: "gegenüber von" },
    { id: "w17", fr: "à côté de", de: "neben" },
    { id: "w18", fr: "entre", de: "zwischen" },
    { id: "w19", fr: "derrière", de: "hinter" },
    { id: "w20", fr: "devant", de: "vor" },
    { id: "w21", fr: "tourner", de: "abbiegen" },
    { id: "w22", fr: "continuer", de: "weitergehen" },
    { id: "w23", fr: "traverser", de: "überqueren" },
    { id: "w24", fr: "le coin", de: "die Ecke" },
    { id: "w25", fr: "c'est loin ?", de: "ist es weit?" },
    { id: "w26", fr: "à pied", de: "zu Fuß" },
    { id: "w27", fr: "en voiture", de: "mit dem Auto" },
    { id: "w28", fr: "le taxi", de: "das Taxi" },
    { id: "w29", fr: "le centre-ville", de: "die Innenstadt" },
    { id: "w30", fr: "l'office de tourisme", de: "das Tourismusbüro" },
  ]},
  hotel: { name: "Im Hotel", icon: "🏨", level: "A2", words: [
    { id: "h01", fr: "l'hôtel", de: "das Hotel" },
    { id: "h02", fr: "la chambre", de: "das Zimmer" },
    { id: "h03", fr: "la réservation", de: "die Reservierung" },
    { id: "h04", fr: "la réception", de: "die Rezeption" },
    { id: "h05", fr: "la clé", de: "der Schlüssel" },
    { id: "h06", fr: "une chambre simple", de: "ein Einzelzimmer" },
    { id: "h07", fr: "une chambre double", de: "ein Doppelzimmer" },
    { id: "h08", fr: "le lit", de: "das Bett" },
    { id: "h09", fr: "la salle de bain", de: "das Badezimmer" },
    { id: "h10", fr: "la douche", de: "die Dusche" },
    { id: "h11", fr: "la serviette", de: "das Handtuch" },
    { id: "h12", fr: "l'ascenseur", de: "der Aufzug" },
    { id: "h13", fr: "le rez-de-chaussée", de: "das Erdgeschoss" },
    { id: "h14", fr: "l'étage", de: "das Stockwerk" },
    { id: "h15", fr: "la vue", de: "die Aussicht" },
    { id: "h16", fr: "le balcon", de: "der Balkon" },
    { id: "h17", fr: "la piscine", de: "der Pool" },
    { id: "h18", fr: "le parking", de: "der Parkplatz" },
    { id: "h19", fr: "le Wi-Fi", de: "das WLAN" },
    { id: "h20", fr: "la nuit", de: "die Nacht" },
    { id: "h21", fr: "arriver", de: "ankommen" },
    { id: "h22", fr: "partir", de: "abreisen" },
    { id: "h23", fr: "la valise", de: "der Koffer" },
    { id: "h24", fr: "le passeport", de: "der Reisepass" },
    { id: "h25", fr: "la climatisation", de: "die Klimaanlage" },
    { id: "h26", fr: "le chauffage", de: "die Heizung" },
    { id: "h27", fr: "le petit-déjeuner inclus", de: "Frühstück inklusive" },
    { id: "h28", fr: "complet", de: "ausgebucht" },
    { id: "h29", fr: "disponible", de: "verfügbar" },
    { id: "h30", fr: "la carte d'identité", de: "der Personalausweis" },
  ]},
  strand: { name: "Am Strand & Freizeit", icon: "🏖️", level: "A2", words: [
    { id: "s01", fr: "la plage", de: "der Strand" },
    { id: "s02", fr: "la mer", de: "das Meer" },
    { id: "s03", fr: "le soleil", de: "die Sonne" },
    { id: "s04", fr: "la crème solaire", de: "die Sonnencreme" },
    { id: "s05", fr: "les lunettes de soleil", de: "die Sonnenbrille" },
    { id: "s06", fr: "le maillot de bain", de: "der Badeanzug" },
    { id: "s07", fr: "la serviette de plage", de: "das Strandtuch" },
    { id: "s08", fr: "nager", de: "schwimmen" },
    { id: "s09", fr: "se baigner", de: "baden" },
    { id: "s10", fr: "le sable", de: "der Sand" },
    { id: "s11", fr: "les vagues", de: "die Wellen" },
    { id: "s12", fr: "le parasol", de: "der Sonnenschirm" },
    { id: "s13", fr: "la glace", de: "das Eis" },
    { id: "s14", fr: "le vélo", de: "das Fahrrad" },
    { id: "s15", fr: "la promenade", de: "der Spaziergang" },
    { id: "s16", fr: "se promener", de: "spazieren gehen" },
    { id: "s17", fr: "le musée", de: "das Museum" },
    { id: "s18", fr: "le cinéma", de: "das Kino" },
    { id: "s19", fr: "le parc", de: "der Park" },
    { id: "s20", fr: "la montagne", de: "der Berg" },
    { id: "s21", fr: "le lac", de: "der See" },
    { id: "s22", fr: "la forêt", de: "der Wald" },
    { id: "s23", fr: "la randonnée", de: "die Wanderung" },
    { id: "s24", fr: "le coucher de soleil", de: "der Sonnenuntergang" },
    { id: "s25", fr: "les vacances", de: "der Urlaub" },
    { id: "s26", fr: "se reposer", de: "sich ausruhen" },
    { id: "s27", fr: "bronzer", de: "sich sonnen" },
    { id: "s28", fr: "la carte postale", de: "die Postkarte" },
    { id: "s29", fr: "le souvenir", de: "das Andenken" },
    { id: "s30", fr: "profiter de", de: "genießen" },
  ]},
  zahlen: { name: "Zahlen & Uhrzeit", icon: "🔢", level: "A1", words: [
    { id: "z01", fr: "zéro", de: "null" },
    { id: "z02", fr: "un", de: "eins" },
    { id: "z03", fr: "deux", de: "zwei" },
    { id: "z04", fr: "trois", de: "drei" },
    { id: "z05", fr: "quatre", de: "vier" },
    { id: "z06", fr: "cinq", de: "fünf" },
    { id: "z07", fr: "six", de: "sechs" },
    { id: "z08", fr: "sept", de: "sieben" },
    { id: "z09", fr: "huit", de: "acht" },
    { id: "z10", fr: "neuf", de: "neun" },
    { id: "z11", fr: "dix", de: "zehn" },
    { id: "z12", fr: "vingt", de: "zwanzig" },
    { id: "z13", fr: "trente", de: "dreißig" },
    { id: "z14", fr: "quarante", de: "vierzig" },
    { id: "z15", fr: "cinquante", de: "fünfzig" },
    { id: "z16", fr: "soixante", de: "sechzig" },
    { id: "z17", fr: "soixante-dix", de: "siebzig" },
    { id: "z18", fr: "quatre-vingts", de: "achtzig" },
    { id: "z19", fr: "quatre-vingt-dix", de: "neunzig" },
    { id: "z20", fr: "cent", de: "hundert" },
    { id: "z21", fr: "mille", de: "tausend" },
    { id: "z22", fr: "quelle heure est-il ?", de: "wie spät ist es?" },
    { id: "z23", fr: "il est ... heures", de: "es ist ... Uhr" },
    { id: "z24", fr: "midi", de: "Mittag" },
    { id: "z25", fr: "minuit", de: "Mitternacht" },
    { id: "z26", fr: "et quart", de: "Viertel nach" },
    { id: "z27", fr: "et demie", de: "halb" },
    { id: "z28", fr: "moins le quart", de: "Viertel vor" },
    { id: "z29", fr: "le matin", de: "der Morgen" },
    { id: "z30", fr: "l'après-midi", de: "der Nachmittag" },
    { id: "z31", fr: "le soir", de: "der Abend" },
    { id: "z32", fr: "aujourd'hui", de: "heute" },
    { id: "z33", fr: "demain", de: "morgen" },
    { id: "z34", fr: "hier", de: "gestern" },
    { id: "z35", fr: "la semaine", de: "die Woche" },
  ]},
  alltag: { name: "Alltag", icon: "🏠", level: "A2", words: [
    { id: "a01", fr: "la maison", de: "das Haus" },
    { id: "a02", fr: "la famille", de: "die Familie" },
    { id: "a03", fr: "le père", de: "der Vater" },
    { id: "a04", fr: "la mère", de: "die Mutter" },
    { id: "a05", fr: "le frère", de: "der Bruder" },
    { id: "a06", fr: "la soeur", de: "die Schwester" },
    { id: "a07", fr: "les enfants", de: "die Kinder" },
    { id: "a08", fr: "le temps", de: "das Wetter" },
    { id: "a09", fr: "il fait beau", de: "es ist schön" },
    { id: "a10", fr: "il fait chaud", de: "es ist warm" },
    { id: "a11", fr: "il fait froid", de: "es ist kalt" },
    { id: "a12", fr: "il pleut", de: "es regnet" },
    { id: "a13", fr: "il neige", de: "es schneit" },
    { id: "a14", fr: "le nuage", de: "die Wolke" },
    { id: "a15", fr: "le vent", de: "der Wind" },
    { id: "a16", fr: "la tête", de: "der Kopf" },
    { id: "a17", fr: "le bras", de: "der Arm" },
    { id: "a18", fr: "la jambe", de: "das Bein" },
    { id: "a19", fr: "le dos", de: "der Rücken" },
    { id: "a20", fr: "le ventre", de: "der Bauch" },
    { id: "a21", fr: "le pantalon", de: "die Hose" },
    { id: "a22", fr: "la robe", de: "das Kleid" },
    { id: "a23", fr: "la chemise", de: "das Hemd" },
    { id: "a24", fr: "les chaussures", de: "die Schuhe" },
    { id: "a25", fr: "le manteau", de: "der Mantel" },
    { id: "a26", fr: "le chapeau", de: "der Hut" },
    { id: "a27", fr: "le chien", de: "der Hund" },
    { id: "a28", fr: "le chat", de: "die Katze" },
    { id: "a29", fr: "aimer", de: "lieben / mögen" },
    { id: "a30", fr: "manger", de: "essen" },
    { id: "a31", fr: "boire", de: "trinken" },
    { id: "a32", fr: "dormir", de: "schlafen" },
    { id: "a33", fr: "parler", de: "sprechen" },
    { id: "a34", fr: "écouter", de: "zuhören" },
    { id: "a35", fr: "regarder", de: "anschauen" },
  ]},
  notfall: { name: "Notfälle & Arztbesuch", icon: "🚑", level: "B1", words: [
    { id: "n01", fr: "au secours !", de: "Hilfe!" },
    { id: "n02", fr: "appelez la police !", de: "rufen Sie die Polizei!" },
    { id: "n03", fr: "appelez une ambulance !", de: "rufen Sie einen Krankenwagen!" },
    { id: "n04", fr: "le médecin", de: "der Arzt" },
    { id: "n05", fr: "l'hôpital", de: "das Krankenhaus" },
    { id: "n06", fr: "la pharmacie", de: "die Apotheke" },
    { id: "n07", fr: "j'ai mal à...", de: "mir tut ... weh" },
    { id: "n08", fr: "j'ai mal à la tête", de: "ich habe Kopfschmerzen" },
    { id: "n09", fr: "j'ai mal au ventre", de: "ich habe Bauchschmerzen" },
    { id: "n10", fr: "j'ai de la fièvre", de: "ich habe Fieber" },
    { id: "n11", fr: "je suis malade", de: "ich bin krank" },
    { id: "n12", fr: "je suis allergique à...", de: "ich bin allergisch gegen..." },
    { id: "n13", fr: "le médicament", de: "das Medikament" },
    { id: "n14", fr: "l'ordonnance", de: "das Rezept" },
    { id: "n15", fr: "la douleur", de: "der Schmerz" },
    { id: "n16", fr: "le dentiste", de: "der Zahnarzt" },
    { id: "n17", fr: "les urgences", de: "die Notaufnahme" },
    { id: "n18", fr: "le pompier", de: "der Feuerwehrmann" },
    { id: "n19", fr: "la police", de: "die Polizei" },
    { id: "n20", fr: "j'ai perdu...", de: "ich habe ... verloren" },
    { id: "n21", fr: "on m'a volé...", de: "man hat mir ... gestohlen" },
    { id: "n22", fr: "le portefeuille", de: "die Geldbörse" },
    { id: "n23", fr: "le téléphone", de: "das Telefon" },
    { id: "n24", fr: "l'assurance", de: "die Versicherung" },
    { id: "n25", fr: "le numéro d'urgence", de: "die Notrufnummer" },
    { id: "n26", fr: "c'est urgent", de: "es ist dringend" },
    { id: "n27", fr: "aidez-moi", de: "helfen Sie mir" },
    { id: "n28", fr: "je ne me sens pas bien", de: "mir geht es nicht gut" },
    { id: "n29", fr: "la piqûre", de: "die Spritze" },
    { id: "n30", fr: "le pansement", de: "das Pflaster" },
  ]}
};

const EINSTUFUNG_FRAGEN = [
  { frage: "Wie sagt man 'Guten Tag' auf Französisch?", optionen: ["Bonjour", "Bonsoir", "Salut", "Merci"], antwort: 0, level: "A1" },
  { frage: "Was bedeutet 'merci'?", optionen: ["bitte", "danke", "hallo", "tschüss"], antwort: 1, level: "A1" },
  { frage: "Welches Wort bedeutet 'ja'?", optionen: ["non", "oui", "bien", "mal"], antwort: 1, level: "A1" },
  { frage: "'Le pain' bedeutet...?", optionen: ["der Wein", "der Käse", "das Brot", "das Wasser"], antwort: 2, level: "A1" },
  { frage: "'Ich heiße...' auf Französisch?", optionen: ["je suis...", "je m'appelle...", "j'ai...", "je vais..."], antwort: 1, level: "A1" },
  { frage: "'Das Wasser' auf Französisch?", optionen: ["le vin", "le lait", "l'eau", "le jus"], antwort: 2, level: "A1" },
  { frage: "'Trois' bedeutet...?", optionen: ["zwei", "drei", "vier", "fünf"], antwort: 1, level: "A1" },
  { frage: "'Au revoir' bedeutet...?", optionen: ["guten Tag", "guten Abend", "auf Wiedersehen", "willkommen"], antwort: 2, level: "A1" },
  { frage: "'Ich hätte gern einen Kaffee' auf Französisch?", optionen: ["Je veux un café", "Je voudrais un café", "Je prends un café", "Je bois un café"], antwort: 1, level: "A2" },
  { frage: "'Wie viel kostet das?' auf Französisch?", optionen: ["C'est combien ?", "Combien ça coûte ?", "Quel prix ?", "C'est cher ?"], antwort: 1, level: "A2" },
  { frage: "Welcher Artikel passt? __ maison", optionen: ["le", "la", "les", "un"], antwort: 1, level: "A2" },
  { frage: "'Je suis allé au marché' — welche Zeitform?", optionen: ["Présent", "Imparfait", "Passé composé", "Futur"], antwort: 2, level: "A2" },
  { frage: "'À gauche' bedeutet...?", optionen: ["nach rechts", "nach links", "geradeaus", "zurück"], antwort: 1, level: "A2" },
  { frage: "Wie bildet man die Verneinung von 'Je sais'?", optionen: ["Je sais non", "Je ne sais pas", "Je pas sais", "Ne je sais"], antwort: 1, level: "A2" },
  { frage: "'Quatre-vingts' ist welche Zahl?", optionen: ["40", "60", "80", "90"], antwort: 2, level: "A2" },
  { frage: "Welche Form ist Conditionnel von 'manger' (je)?", optionen: ["je mange", "je mangeais", "je mangerais", "je mangerai"], antwort: 2, level: "B1" },
  { frage: "Si j'avais le temps, je __ au cinéma.", optionen: ["vais", "allais", "irai", "irais"], antwort: 3, level: "B1" },
  { frage: "'Il faut que tu partes' bedeutet...?", optionen: ["Du kannst gehen", "Du musst gehen", "Du willst gehen", "Du gehst"], antwort: 1, level: "B1" },
  { frage: "Wie ersetzt man 'les livres' durch ein Pronomen?", optionen: ["leur", "les", "en", "y"], antwort: 1, level: "B1" },
  { frage: "'Bien que' verlangt welchen Modus?", optionen: ["Indicatif", "Conditionnel", "Subjonctif", "Impératif"], antwort: 2, level: "B1" },
];
